import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import "./globals.css";
import 'swiper/css';
import { Box, CssBaseline } from "@mui/material";
import Layout from "@/components/Layout";
import { Suspense } from "react";
import Loading from '@/components/Loading'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppRouterCacheProvider>

          <Box sx={{ display: 'flex', height: '100%' }}>
            <CssBaseline />
         
              <Layout>{children}</Layout>
   

          </Box>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
